### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by resslr** [Hamza12700/drash#1]
So this removes it and stores it for a bit from what I understand, how long until the file gets deleted after drash gets ran? Like what is the restore period?

**Comment by Hamza12700** [comment]
No, unfortunately I haven't implemented that feature yet. It doesn't delete files automatically. It would only delete it if you tell it to.
Use `remove` subcommand to remove a single or multiple files, or if you want to delete everything in the drashcan you use the `empty` subcommand. The `empty` subcommand accepts an argument `-y or --yes` which will not prompt you to confirm.
